
services:
  home:
    build:
      context: .
      dockerfile: home/Dockerfile
    ports:
      - "6003:6003"
    networks:
      - mf-network
    environment:
      - NODE_ENV=production
      - NEXT_PRIVATE_LOCAL_WEBPACK=true
      - DOCKER_ENV=true
      - NEXT_PUBLIC_HOST_URL: "http://home-nxt:6003"
      - ANNOUNCEMENT_URL: "http://announcement-nxt:6004"
      - POPUP_URL: "http://popup-nxt:6005"
      - TESTIMONIAL_URL: "http://testimonial-nxt:6006"
      - FOOTER_URL: "http://footer-nxt:6007"
      
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6003/"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  announcement:
    build:
      context: .
      dockerfile: announcement/Dockerfile
    ports:
      - "6004:6004"
    networks:
      - mf-network
    environment:
      - NODE_ENV=production
      - NEXT_PRIVATE_LOCAL_WEBPACK=true
      - DOCKER_ENV=true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6004/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - home

  popup:
    build:
      context: .
      dockerfile: popup/Dockerfile
    ports:
      - "6005:6005"
    networks:
      - mf-network
    environment:
      - NODE_ENV=production
      - NEXT_PRIVATE_LOCAL_WEBPACK=true
      - DOCKER_ENV=true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6005/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - home

  testimonial:
    build:
      context: .
      dockerfile: testimonial/Dockerfile
    ports:
      - "6006:6006"
    networks:
      - mf-network
    environment:
      - NODE_ENV=production
      - NEXT_PRIVATE_LOCAL_WEBPACK=true
      - DOCKER_ENV=true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6006/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - home

  footer:
    build:
      context: .
      dockerfile: testimonial/Dockerfile
    ports:
      - "6007:6007"
    networks:
      - mf-network
    environment:
      - NODE_ENV=production
      - NEXT_PRIVATE_LOCAL_WEBPACK=true
      - DOCKER_ENV=true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6007/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - home

networks:
  mf-network:
    driver: bridge
