apiVersion: v1
kind: Service
metadata:
  name: announcement-nxt
spec:
  type: NodePort
  selector:
    app: announcement-nxt
  ports:
    - port: 6004
      targetPort: 6004
      nodePort: 31021
      protocol: TCP
      name: http