apiVersion: v1
kind: Service
metadata:
  name: home-nxt
spec:
  type: NodePort
  selector:
    app: home-nxt
  ports:
    - port: 6003
      targetPort: 6003
      nodePort: 30030
      protocol: TCP
      name: http