apiVersion: v1
kind: Service
metadata:
  name: popup-nxt
spec:
  type: NodePort
  selector:
    app: popup-nxt
  ports:
    - port: 6005
      targetPort: 6005
      nodePort: 31022
      protocol: TCP
      name: http